### ISSUE TITLE
Blurred example in readme is hard on the eyes.

### ISSUE THREAD

**Issue by aglassman** [WatermarkInsights/dm-web-profile-themes#7]
It would be better to have an example of the theme using mock data rather than the blurred example.  The blurred example is hard on the eyes, and distracts from what the theme actually looks like.  It would be nice to see what it actually looks like with Lorem Ipsum data if it's going to be in the README.

**Comment by kylehalleman** [comment]
We could add a screenshot with sample data. Alternatively we could link to a demo site, which might be better because it will give a better representation of the theme.

**Comment by kylehalleman** [comment]
Closing, addressed by #8.
